[COR-106] [COR-107] [COR-108] Add Latency Metrics
nakji-network/connector pull request #66
Opened 2022-10-29 05:58 UTC by gunnarsundberg

- Propagate traces through context instead of spans so that we may pass baggage in addition to spans
- Add rpc latency to ethereum subscription
- Add latency observations to baggage that will be used to derive metrics
- Add metrics exporter
- Add histogram metrics for latency metrics

2022-10-29 15:06 UTC, rukolahasser requested changes
1. There are only 4 spans, we need 5. It's missing an end to end span.
2. How do I check the histogram in jaeger?

2022-10-29 18:22 UTC, gunnarsundberg commented
> * There are only 4 spans, we need 5. It's missing an end to end span.
> * How do I check the histogram in jaeger?

e2e is derived from other spans and exported as a metric to the collector instead of having its own span. jaeger does not support otel metrics or any other metrics capabilities so you cannot see the histograms. if you check out port 9999 of the collector and go to `/metrics` endpoint, you will be able to see the raw data. if you want to visualize it, it will need to be exported to something like our prometheus/grafana instance.

2022-10-30 00:12 UTC, gunnarsundberg commented on chain/ethereum/subscription.go
> +			spanCtx, span := monitor.StartSpan(
this is connector latency span. I have an rpc latency span that starts from block time

2022-10-30 01:07 UTC, rm289 approved these changes
normally I don't and won't approve things, but these are typos (misspellings and one mistake on usage of context.).  I'm moving them forward because no one is on and we cannot afford to lose a day of development until reviewers come online.

2022-10-30 01:11 UTC, rm289 commented
> 1. There are only 4 spans, we need 5. It's missing an end to end span.
> 2. How do I check the histogram in jaeger?

The end to end span can be derived by adding the spans together.  @gunnarsundberg asked me if this was acceptable. I told him deriving times by adding two or more span times is acceptable.  The math will be the same since its simple addition.  
Let's please move this forward, we are running out of time to get this through staging and into prod.

2022-10-30 02:01 UTC, gunnarsundberg commented on monitor/metric.go
> +func ExportLatencyMetrics(ctx context.Context, meter metric.Meter, connName string, env string) {
added!

2022-10-30 02:02 UTC, gunnarsundberg commented on kafkautils/consumer.go
> +	spanName          = "kafka -> consumer"
hmu with a suggestion and I will change it after we push to staging

2022-10-30 02:05 UTC, gunnarsundberg commented on chain/ethereum/subscription.go
> +	Context context.Context
ross wants me to push to staging so I will mark as resolved and address this after I push to staging. can we discuss on slack?

2022-10-30 02:44 UTC, merged